### ISSUE TITLE
What does this project produce as a binary?

### ISSUE THREAD

**Issue by hlide** [DarthTon/HyperBone#3]
An executable? A driver? How to install it? Should it be signed to be usable on 64-bit Windows 7+? Can it work with Microsoft Hyper-Visor activated? And so on...

I think README.md should be more informative about how to use this project and its constraints.

**Comment by DarthTon** [comment]
It produces generic x64 driver with all its requirements. it won't run with any other hardware hypervisor active: hyper-v, vmware, vbox, etc.
People who understand why they need to run this project usually know how to do it.
