### ISSUE TITLE
FIX DPC_WATCHDOG_VIOLATION 

### ISSUE THREAD

**Issue by huoji120** [DarthTon/HyperBone#33]
the DPC_WATCHDOG_VIOLATION  reason is that the vmexit is always running at DPC level and windows will check is hypervisor exist , if is no(hyperbone didn't deal with it) will trigger DPC_WATCHDOG_VIOLATION 
just skip irql elevate function and you will be fine

**Comment by huoji120** [comment]
do not forget that when you are doing hook, some functions may continue DPC level and crash system

**Comment by L1B0** [comment]
Hi, I'm facing a DPC_WATCHDOG_VIOLATION bug when I set a hook on my hypervisor.

And what do you mean that “if is no(hyperbone didn't deal with it)”? What doesn't hyperbone deal with? 

Maybe I have the same problem.

And the second comment, if some functions may continue DPC level, do you know how to avoid that?

Thanks a lot!

**Comment by huoji120** [comment]
你给你的CPUID返回当前存在hypervisor状态就行

**Comment by L1B0** [comment]
我在cpuid产生vm-exit的时候设置了存在hypervisor，看来不是这个原因。
但是“just skip irql elevate function and you will be fine”是什么意思呢？
感谢大佬！
