### ISSUE TITLE
[QUESTION] Controller

### ISSUE THREAD

**Issue by Randshot** [DarthTon/HyperBone#9]
Hey,

is there a way to control the HyperVisor from a user program or do you plan to implement one?

**Comment by DarthTon** [comment]
Yes, you can use any suitable method: IOCTL, pipe, etc. Hyperbone is a windows driver after all. Currently I'm not planning to implement any UM interaction.

**Comment by Randshot** [comment]
Ok, I guess I will have to implement it myself. Anyway, thanks.
